### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by valentinkiryanski** [L1xiaolong/hdr_exposure_fusion#1]
Are you the dev of NoctuCam and are you going to integrate HDR+ by martin marek to Noctucam?

**Comment by L1xiaolong** [comment]
> 

Sorry, I am not a developer of NoctuCam. In fact, I have completed the implementation of HDR+ in python.

**Comment by valentinkiryanski** [comment]
Could you make a windows app where I can put a burst of dng images and then
process them using HDR+? Or an ios app? Thank you!

На четвъртък, 2 декември 2021 г. Walker ***@***.***> написа:

**Comment by L1xiaolong** [comment]
Sorry, this is not on my schedule. 
You can refer to this project: https://github.com/amonod/hdrplus-python
